### ISSUE TITLE
An idea on how to handle boards

### ISSUE THREAD

**Issue by f-r00t** [kryptokrona/hugin-bridge#8]
We should probably discourage/disallow posting in the Home board and make people post in specific boards always instead. In the same way we should have a specific board for each bridge. For example, the Discord bridge should only read messages from the Discord board on Hugin Messenger, and should only post to the Discord board when users write in the #hugin-bridge channel.

Same goes for Telegram etc.

Any thoughts?

**Comment by Swepool** [comment]
Does this mean we would not print any other boards in discord?

**Comment by f-r00t** [comment]
That could be up for discussion. I think the main concern is solved by [09a1c0d](https://github.com/kryptokrona/hugin-bridge/commit/09a1c0ded53d51739bc6fc4b66d28e99da21503b), so I'll close this issue for now.
